# view 경로 설정
spring.mvc.view.prefix = /WEB-INF/jsp/
spring.mvc.view.suffix = .jsp

spring.datasource.driver-class-name = org.mariadb.jdbc.Driver
spring.datasource.url = jdbc:mariadb://xn--oy2bi2kqb200bl3dtpfwov.com:3306/sdh4716
spring.datasource.username = sdh4716
spring.datasource.password = ekgusekgus2@

#mybatis.config-location=mybatis-config.xml

# 깊이에 상관없이 /mappers 하위 경로에 있는 모든 xml문서 사용
mybatis.mapper-locations=classpath:/mappers/**/*.xml